# Generated by Django 5.0.4 on 2024-05-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle_estoque', '0003_item_unidade_item_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
